### ISSUE TITLE
"Failed to load plugin configuration, Error code: 11"

### ISSUE THREAD

**Issue by Jacksaur** [EladKarni/obs-replay-buffer-notify#1]
Followed the instructions given for installation on Windows 10, getting the above error in my logs each time and no sound plays upon saving my replay buffer.
I fully expect I've screwed up the file placements somehow, so any assistance there would be appreciated. File placements are shown below, all the DLLs are in the main OBS directory alongside the exe:
![iKHkxRk](https://user-images.githubusercontent.com/58850292/146637856-9bde9c7c-6fa6-43f0-9e06-a882863fa80a.png)

Full startup log is here: https://pastebin.com/brGWatr1

**Comment by maggaou** [comment]
I also didn't get it to work. I used obs-studio\bin\64bit and obs-studio\obs-plugins\64bit. Using obs-studio\obs-plugins\32bit didn't seem to work. While using obs-studio\obs-plugins\64bit, obs-studio just hangs with 10% cpu-usage when starting it, GUI is not shown.

**Comment by Jacksaur** [comment]
I imagine it's bad ettiquette to link other projects in the issues, but seeing as this project seems to be abandoned I've been having significantly more luck with this script instead:
https://github.com/ntoff/obs_scripts

It only alerts when the Replay Buffer is finished saving though, so I also added a trigger to play a sound when studio mode is toggled and set a sound clip to play for that too. That way I can be certain that OBS recieved the hotkey, and has began the buffer saving process.

**Comment by maggaou** [comment]
Thanks for your reply. I found and used this script: https://gist.github.com/snakecase/e816384a071cec31efbb4b9e429c108d.

**Comment by Jacksaur** [comment]
That looks significantly simpler than the one I was using already, cheers.
Surprising how bloody difficult it is to find these scripts in the first place: Google has been absolutely useless in finding any of these.
